--
-- THANKS TO "BETTER AI" FOR SUGGESTIONS
--
NDefines.NAI.ACCEPTABLE_BALANCE_DEFAULT = 1.50      -- AI wants this advantage to enter battles typically. (There are some exceptions, e.g. offensives.)
NDefines.NAI.ACCEPTABLE_BALANCE_FRIEND_IN_COMBAT = 0.65
NDefines.NAI.ADVISOR_BUDGET_FRACTION = 0.5        -- AI will spend a maximum of this fraction of monthly income on advisor maintenance
NDefines.NAI.AGGRESSIVENESS = 500                 -- Base chance (out of 10000) of AI being willing to start a war each diplomatic tick (~1.5 times a month)
NDefines.NAI.AGGRESSIVENESS_BONUS_EASY_WAR = 900  -- Added to aggressiveness if the war is against a weak or particularily hated enemy
NDefines.NAI.AI_WANT_ACCEPT_CULTURES = 200  	    -- How much the AI values having much development in accepted cultures.
NDefines.NAI.ARMY_BUDGET_FRACTION = 0.4           -- AI will spend a maximum of this fraction of monthly income on army maintenance (based off wartime costs)
NDefines.NAI.ARTILLERY_FRACTION = 0.25            -- Ratio of artillery to infantry AI will build
NDefines.NAI.BIGSHIP_FRACTION = 0.2               -- The proportion of big ships in an AI navy of light ships and big ships (for coastal sea countries, this fraction is mostly galleys)
NDefines.NAI.BORDER_DISTANCE_SCORE_IMPACT = 5.0   -- Border <-> province distance impact on province evaluation
NDefines.NAI.CALL_IN_ALLIES_POWER_RATIO = 2.0     -- AI will only call in allies in an offensive war if their military power ratio to the enemy is less than this
NDefines.NAI.COLONY_BUDGET_FRACTION = 0.6         -- AI will spend a maximum of this amount of monthly ducats for colonies.
NDefines.NAI.CONQUEST_INTEREST_DISTANCE = 150     -- Beyond this range, AI is less interested in conquest of provinces
NDefines.NAI.DEBASE_THRESHOLD = 200               -- AI will not debase if it has more gold than this.
NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 24     -- AI must have at least this many monthly deficits of savings to be willing to deficit spend
-- NDefines.NAI.DEFICIT_SPENDING_MIN_MONTHS = 3   -- AI must have at least this many monthly deficits of savings to be willing to deficit spend
NDefines.NAI.DESIRED_DEFICIT = 0.05               -- AI will try to spend this fraction of their money above their target for long term savings.
NDefines.NAI.DESIRED_SURPLUS = 0.4                -- AI will aim for having at least this fraction of their income as surplus when they don't have large savings
NDefines.NAI.DEVELOPMENT_CAP_BASE = 100           -- AI will not develop provinces that have more development than this or DEVELOPMENT_CAP_MULT*original development (whichever is bigger)
NDefines.NAI.DEVELOPMENT_CAP_MULT = 20
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_BASE_FACTOR = 75             -- AI scoring for fabricating claims is always increased by this as long as the province is a conquest priority
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_NOT_ADJACENT_FACTOR = 1.0    -- AI scoring for fabricating claims if the province is not adjacent
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_OTHER_CB_FACTOR = 1.0        -- AI scoring for fabricating claims if they already have another CB usable on the province
NDefines.NAI.DIPLOMATIC_ACTION_FABRICATE_CLAIM_STRATEGY_FACTOR = 1.0        -- AI scoring for fabricating claims based on strategic conquest priorities
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_AI = 100            -- AI willingness to send gifts to AI nations fighting power balance threat is modulated by this.
NDefines.NAI.DIPLOMATIC_ACTION_GIFT_POWERBALANCE_FACTOR_PLAYER = 100        -- AI willingness to send gifts to human nations fighting power balance threat is modulated by this.
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_ALLY_FACTOR = 70           -- AI scoring for improve relations is increased by this if they have an attitude with 'ally' desire
NDefines.NAI.DIPLOMATIC_ACTION_IMPROVE_RELATIONS_BEFRIEND_FACTOR = 70       -- AI scoring for improve relations is increased by this if they have an attitude with 'befriend' desire
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_INDEBTED_FACTOR = 30               -- AI scoring for giving subsidies to an ally in heavy debt
NDefines.NAI.DIPLOMATIC_ACTION_SUBSIDIES_POWERBALANCE_FACTOR = 70           -- AI scoring to give subsidies to nations blocking/fighting power balance threat.
NDefines.NAI.ESTATE_INTERACTION_THRESHOLD = 25.0
NDefines.NAI.ESTATE_MAX_PRIVILEDGES = 5
NDefines.NAI.ESTATE_MAX_WANTED_INFLUENCE = 85.0
NDefines.NAI.ESTATE_MIN_WANTED_CROWNLAND = 11.0
NDefines.NAI.ESTATE_PRIVILEGE_GRANT_THRESHOLD = 7.0
NDefines.NAI.ESTATE_PRIVILEGE_REVOKE_THRESHOLD = 7.0
NDefines.NAI.EXTRA_SURPLUS_WHEN_NEEDING_BUILDINGS = 0.6         -- AI will aim for having at least this fraction of their income as additional surplus when they need buildings
NDefines.NAI.FOG_OF_WAR_FORGET_CHANCE = 2                       -- Daily percentage chance of AI forgetting a unit that's hidden in Fog of War.
NDefines.NAI.FORCE_COMPOSITION_CHANGE_TECH_LEVEL = 16           -- Tech level at which AI will double its artillery fraction
NDefines.NAI.HOME_FLEET_MAX_RATIO = 0.6 	                      -- Maximum proportion of warships in home fleet.
NDefines.NAI.HRE_FORCE_JOIN_DESIRE_PER_MISSING_PRINCE = 5.0     -- Multiplicative factor per HRE missing prince for the purpose of calculating the desire of use the force join HRE treaty.
NDefines.NAI.IMPORANT_PROVINCE_THRESHOLD = 0.02                 -- AI will try to defend provinces under threat worth more than this percentage of total development
NDefines.NAI.INCOME_SAVINGS_FRACTION = 0.2                      -- AI will reserve this amount of their surplus for long-term savings
NDefines.NAI.INVADING_MAX_AWAY_RATIO = 0.7 	                    -- AI will never send more than this ratio to invade (Measured in strength)
NDefines.NAI.INVASION_ARMY_LOOKUP_INTERVAL_ON_FAILURE = 5 	    -- If AI fails to find an army for an invasion it will try again in this number of days
NDefines.NAI.MAX_ARMIES_NEW_REGION_ASSIGN_ALGORITHM = 40  	    -- Max. amount of armies to use in new region assignment algorithm (fall back to old one)
NDefines.NAI.MAX_BUILDING_COST_INCOME_MONTHS = 120              -- AI will not save up for a building that costs more than their monthly income * this, if there are cheaper alternatives
NDefines.NAI.MAX_CAV_PERCENTAGE = 30                            -- For modding, actual ratio is dynamically computed but will be no higher than this.
NDefines.NAI.MAX_SAVINGS = 36                                   -- AI will keep a maximum of this * their monthly income in long-term savings
NDefines.NAI.MIN_CAV_PERCENTAGE = 0                             -- AI will always try to have at least this many % of their army as cav, regardless of time in the game.
NDefines.NAI.MISSIONARY_MAINTENANCE_SHARE = 0.8							    -- The most an AI will spend of its income on a missionary
NDefines.NAI.ONLY_INFANTRY_MERCS = 0                            -- Set to 0 to let AI hire artillery and cavalry mercenaries.
NDefines.NAI.OVER_FORCELIMIT_AVOIDANCE_FACTOR = 5               -- The higher this number is, the less willing the AI will be to exceed forcelimits
NDefines.NAI.PEACE_ALLY_DESPERATION_MULT = 1.5                  -- Multiplies PEACE_DESPERATION_FACTOR for allies in a war
NDefines.NAI.PEACE_ALLY_REBELS_MULT = 2.0                       -- Multiplies PEACE_REBELS_FACTOR for allies in a war
NDefines.NAI.PEACE_COALITION_FACTOR = 20                        -- AI unwillingness to peace based on being in a coalition war
NDefines.NAI.PEACE_DESPERATION_FACTOR = 45                      -- AI willingness to peace based on desperation from occupied homelands
NDefines.NAI.PEACE_REBELS_FACTOR = 30                           -- AI willingness to peace based on number of revolts in their provinces
NDefines.NAI.PEACE_TERMS_GOLD_BASE_MULT = 0.3
NDefines.NAI.PEACE_TERMS_PROVINCE_CLAIM_MULT = 3.0              -- AI desire for a province is multiplied by this if it has a claim on it
NDefines.NAI.PEACE_TERMS_PROVINCE_CORE_MULT = 4.0               -- AI desire for a province is multiplied by this if it has a core on it
NDefines.NAI.PEACE_TERMS_PROVINCE_IMPERIAL_LIBERATION_MULT = 5.0    -- AI Emperor's desire for a province is multiplied by this if this is an Imperial Liberation CB war.
NDefines.NAI.PEACE_TERMS_PROVINCE_NOT_CULTURE_MULT = 1.0        -- AI desire for a province is multiplied by this if it is not the same culture
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_CB_MULT = 1.0              -- AI desire for a province is multiplied by this if it doesn't have a valid cb for it (only used when annexing, not applied to cores)
NDefines.NAI.PEACE_TERMS_PROVINCE_NO_INTEREST_MULT = 0.4        -- AI desire for a province is multiplied by this if it is not on their conquest list
NDefines.NAI.PEACE_TERMS_PROVINCE_VASSAL_MULT = 0.9             -- AI desire for a province is multiplied by this if it would go to their vassal instead of themselves
NDefines.NAI.PEACE_TERMS_PROVINCE_WARGOAL_MULT = 3.0            -- AI desire for a province is multiplied by this if it is the wargoal
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_BASE_MULT = 0.2        -- AI desire for war reparations through peace
NDefines.NAI.PEACE_TERMS_WAR_REPARATIONS_MIN_INCOME_RATIO = 0.2   -- AI only wants war reparations if other country has at least this % of their income
NDefines.NAI.POWERFUL_ALLY_PENALTY = 90                         -- Penalty on alliance for them already having a powerful ally if much stronger
-- NDefines.NAI.PRESS_THEM_FURTHER = 1 DO NOT ENABLE THIS CURRENTLY AT 1.30.3, after ~5 years it crashes the game. [Official] This makes AI that has been promised land require that the enemy is pressed further if they think it is possible. Set to 1 to activate
NDefines.NAI.PS_SHORT_TERM_POOL = 50                            -- Max power AI will store in its short-term spending pool
NDefines.NAI.PURSUE_DISTANCE = 200                              -- AI will not pursue armies retreating to a province further away than this
NDefines.NAI.REGIMENTS_PER_GENERAL = 20                         -- AI will want one general for every this number of regiments (will not exceed free leader pool)
NDefines.NAI.REGION_PLANNING_HOMELAND_PRIORIZATION = 5.0   	    -- Homeland priorization when assigning armies to regions (only applied when actually threatened)
NDefines.NAI.REPAY_LOAN_BASE_AI_DESIRE = 40.0 	                -- AI scoring for repaying loans, multiplied by (MAX(budget - other loans, 0) * number_of_loans)/cost
NDefines.NAI.TRADE_POLICY_AT_WAR_PER_PROVINCE_SCORE = 20.0  	  -- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRADE_POLICY_PREPARING_FOR_WAR_PER_PROVINCE_SCORE = 20.0     -- Score per enemy province while preparing war for attack bonus trade policy (if selectable)
NDefines.NAI.TRANSPORT_FRACTION = 0.3                           -- Max fraction of naval forcelimit that should be transports
NDefines.NAIEconomy.ARMY_FRACTION_MILITARIST = 0.7
NDefines.NAIEconomy.ARMY_FRACTION_PEACEFUL = 0.4
NDefines.NAIEconomy.FORT_FRACTION_CAPITALIST = 0.5
NDefines.NAIEconomy.FORT_FRACTION_MILITARIST = 0.6
NDefines.NAIEconomy.LOAN_REPAYMENT_SAVINGS_PRIORITY = 0.8
NDefines.NAIEconomy.MILITARY_FOCUS_DEFAULT = 2.0
NDefines.NAIEconomy.MILITARY_FOCUS_LOWER_BOUND = 0.1
NDefines.NAIEconomy.MILITARY_FOCUS_UPPER_BOUND = 3.0
NDefines.NAIEconomy.MISSIONARY_FRACTION = 0.3
NDefines.NAIEconomy.NAVY_FRACTION_CAPITALIST = 0.8
NDefines.NAIEconomy.NAVY_FRACTION_PEACEFUL = 0.6
NDefines.NAIEconomy.REBEL_THREAT_MILITARIZE_THRESHOLD = 0.9 	-- Above what rebel threat should the AI militarize (i.e. focus spending on armies)
